### ISSUE TITLE
Omitting sensitive URLs

### ISSUE THREAD

**Issue by philipithomas** [BaseSecrete/active_analytics#1]
I reviewed the documentation, and don't see a way to omit sensitive URLs. For example, a password reset URL shouldn't show up in analytics or the logs. 

Is there a way to do this today in ActiveAnalytics? If yes - then please document it in the ReadMe. If not, then this is a feature request to be able to omit particular controllers from ActiveAnalytics!

**Comment by alexisbernard** [comment]
Thanks for your comment. I have tried to make it more clear in the README : https://github.com/BaseSecrete/active_analytics/commit/e7939e26bb766073fc63d7b21fe5bbd07c3b1de9

Let me know if it makes more sens.

**Comment by philipithomas** [comment]
Yes, that solves it. Thank you!
