### ISSUE TITLE
Page (path) should not be downcased

### ISSUE THREAD

**Issue by n-b** [BaseSecrete/active_analytics#12]
(First, thanks a lot for making this gem 💚)

In [ViewsPerDay#append](https://github.com/BaseSecrete/active_analytics/commit/6042520bd2a91873b1ddc7b6ebaf801a25fd2f5e#diff-e468c3a9e09acbf0c255cb73d896e3fe897256781cfc717596d123c74511abe1R96), the params are all `downcase`d, including `params[:page]`, the path.

I understand that this is to track `/path/to/document` and `/Path/To/Document` together, but URL paths are case sensitive. Even though some servers will happily accept both cases, it’s not the spec.

I suggest to simply remove the line 96:
```diff
- params[:page] = params[:page].downcase if params[:page]
```

A few more notes:
- we noticed it in a scenario where a component of the path is a generated token, with uppercase and lowercase parameters; 
- the regular rails routes are case sensitive. `localhost:3000/analytics` works, but `localhost:3000/ANALYTICS` doesn’t.

**Comment by alexisbernard** [comment]
You are right, it should be case sensitive.
