### ISSUE TITLE
Monkey Patching Authorization Checks into Active Analytics

### ISSUE THREAD

**Issue by jonmchan** [BaseSecrete/active_analytics#13]
If you guys have a wiki or something, it might be nice to document how to monkey patch authorization check to Active Analytics. I did a quick and dirty one using the following code:

```
# config/initializers/active_analytics.rb

# monkey patch stuff
module ActiveAnalytics
  module ApplicationControllerAdminValidation
    extend ActiveSupport::Concern
    included do
      before_action :require_admin
    end

    def require_admin
      raise ActionController::RoutingError.new("Not found") unless current_user.try(:admin?)
    end
  end
end

Rails.application.config.to_prepare do
  ActiveAnalytics::ApplicationController.include ActiveAnalytics::ApplicationControllerAdminValidation
end
```

If you want it to be friendlier, you can have it redirect to a login or something. I just wanted people snooping around not to know about the analytics at all and just get a 404.

**Comment by alexisbernard** [comment]
There is already a section for that in the README: https://github.com/BaseSecrete/active_analytics?tab=readme-ov-file#authentication-and-permissions.

**Comment by jonmchan** [comment]
Awesome.. that is great. I notice my methodology is a bit different than the README. I'll leave a few keywords for google and close this issue.

Here's how to monkey patch authorization/authentication into active analytics using config/initializers, tested on rails 7.1 and Sorcery. Probably works on devise as well.
