### ISSUE TITLE
ActionView::Template::Error (active_analytics/application.css)

### ISSUE THREAD

**Issue by wasifhossain** [BaseSecrete/active_analytics#2]
Hi, thanks for the nice gem!

when we tried to visit the `/analytics` page since setting up the gem, the development server ended up with the following error:
```
Completed 500 Internal Server Error in 110ms (ActiveRecord: 1.5ms | Allocations: 227136)


  
ActionView::Template::Error (active_analytics/application.js):
     7:     <%= csp_meta_tag %>
     8: 
     9:     <%= stylesheet_link_tag "active_analytics/application", media: "all" %>
    10:     <%= javascript_include_tag "active_analytics/application" %>
    11:   </head>
    12: 
    13:   <body>
  
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:372:in `raise_unless_precompiled_asset'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:338:in `digest_path'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:326:in `asset_path'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:103:in `block in resolve_asset_path'
sprockets-rails (3.2.2) lib/sprockets/rails/helper.rb:243:in `block in resolve_asset'
```
I should add that we are using webpacker to manage all our assets (though sprockets is also enabled).

Fortunately it works if we add the following lines in `app/assets/config/manifest.js` :raised_hands:
```js
//= link active_analytics/application.css
//= link active_analytics/application.js
```

I was wondering if getting started with this awesome gem could be made smoother just by following the current Readme file. 

Luckily I found that our app works without the above lines in the `manifest.js` file if i add the following lines in  `lib/active_analytics/engine.rb`
```rb
module ActiveAnalytics
  class Engine < ::Rails::Engine
    isolate_namespace ActiveAnalytics

    initializer "active_analytics.assets.precompile" do |app|
      app.config.assets.precompile += %w( active_analytics/application.js active_analytics/application.css )
    end
  end
end
```
by following the official doc: https://guides.rubyonrails.org/engines.html#separate-assets-and-precompiling

Thanks!

#### Stack:

Ruby: 2.7.3
Rails: 6.1.3.2

**Comment by alexisbernard** [comment]
Thanks for the report. I have added your suggestion 13e089227771c2d30b61b080b2b7314a05ea6817.
