### ISSUE TITLE
Sass::SyntaxError - $color: "var(--color-bg)" is not a color for `rgba':

### ISSUE THREAD

**Issue by GPif** [BaseSecrete/active_analytics#3]
After basic install, and once added the :
```ruby
# config/routes.rb
authenticate :user, -> (u) { u.admin? } do # Supposing there is a User#admin? method
  mount ActiveAnalytics::Engine, at: "analytics" # http://localhost:3000/analytics
end
```
I get ```Sass::SyntaxError - $color: "var(--color-bg)" is not a color for `rgba':``` error.

**Comment by alexisbernard** [comment]
There is no sass files, so I don't really understand from where is this error coming. Can you try with directly with the version from GitHub ?

```ruby
gem "active_analytics", git: "https://github.com/BaseSecrete/active_analytics.git", ref: "6107b53a230698e9104c0cbb188719a18a0df0ad"

**Comment by alexisbernard** [comment]
There is no more asset pipeline dependency so I close the issue.

Not released yet, but if you want to give it another try : `gem "active_analytics", git: "https://github.com/BaseSecrete/active_analytics.git"`.
