### ISSUE TITLE
Unable to install when using an alternative asset bundler

### ISSUE THREAD

**Issue by shroy** [BaseSecrete/active_analytics#5]
I really like what you all are building here. It looks like a great gem! Unfortunately, when attempting to install the engine using the `rails active_analytics:install:migrations` command, I am presented with this error:

```
NoMethodError: undefined method `assets' for #<Rails::Application::Configuration
```

I am running a Rails 7.0.2 app using `vite.js` for all asset bundling. Sprockets and the asset pipeline are entirely removed, along with all references to `config.assets`. 

FWIW, when googling this error, I found the [`hotwire-rails` repo](https://github.com/hotwired/hotwire-rails/issues/30) had to deal with it as well. Their solution was to wrap the asset installation in a conditional and (I assume) supply an npm package as an alternative. For reference, the PR for that can be found [here](https://github.com/hotwired/turbo-rails/pull/17). Hope that helps!

**Comment by alexisbernard** [comment]
Thanks for the kind words :-)

I added the condition to prevent from crashing when there is no asset pipeline. However I don't feel like managing an external npm package for the assets. Feel free to do it although.

**Comment by shroy** [comment]
I can completely understand. I was attempting to use this on a side project that consumes my own free time. Perhaps I'll revisit it in the future if I'm looking for something new to do.

Thanks for the response!
