### ISSUE TITLE
uninitialized constant ActiveAnalytics::ApplicationHelper

### ISSUE THREAD

**Issue by mateuszbialowas** [BaseSecrete/active_analytics#7]
When I run `bundle exec rails zeitwerk:check` or try to run rails server then I have error:
```
rails aborted!
NameError: uninitialized constant ActiveAnalytics::ApplicationHelper

      Object.const_get(camel_cased_word)
            ^^^^^^^^^^
Did you mean?  ActiveAnalytics::ApplicationController
```
How to fix this?

![image](https://user-images.githubusercontent.com/58574619/211164051-cc6b4bfe-d4b4-48a7-9581-2979d8118287.png)

**Comment by mateuszbialowas** [comment]
I moved authorization to the controller folder and now its working 
![image](https://user-images.githubusercontent.com/58574619/211164733-1d899c18-06ab-40bc-930f-6fce160776a2.png)

**Comment by mateuszbialowas** [comment]
When I moved to the controller dir, then I could run server, but when I deployed this then I have this error now
![image](https://user-images.githubusercontent.com/58574619/211165246-7e17af81-e2b9-4575-b7f4-f66d2268f057.png)

**Comment by alexisbernard** [comment]
Hi, what are you Rails and Ruby versions ?

PS: I just saw it in your last comment after sending mine.

**Comment by mateuszbialowas** [comment]
@alexisbernard 
I have:
ruby '3.1.0'
'rails', '~> 7.0.2'

Finally, I did this and now it is working. 
![image](https://user-images.githubusercontent.com/58574619/211870857-999496eb-e3a7-494c-972a-47ed0a6d01f3.png)

**Comment by alexisbernard** [comment]
Glad you found a solution. But it might break in the future if require_date_range and current_views_per_days change.

I have updated the README (https://github.com/BaseSecrete/active_analytics#authentication-and-permissions). It should be cleaner and more robust.

I close the issue, but let me know in the case it doesn't work for you.
